### ISSUE TITLE
Bug: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by tangytang** [iTwin/viewer#172]
Unable to get Viewer App started due to error in the console:
![Screenshot from 2022-05-26 16-59-18](https://user-images.githubusercontent.com/19624580/170455508-982a1d67-a348-4b07-8f7b-6e0cdb74c4d6.png)

Error Code: 

​ Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of HeaderRow which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at t (http://localhost:3000/static/js/vendors~main.chunk.js:517983:89125)
    at div
    at t (http://localhost:3000/static/js/vendors~main.chunk.js:517983:83671)
    at div
    at t (http://localhost:3000/static/js/vendors~main.chunk.js:517983:76743)
    at div
    at div
    at t (http://localhost:3000/static/js/vendors~main.chunk.js:517983:57330)
    at ElementResizeObserver (http://localhost:3000/static/js/vendors~main.chunk.js:352917:34)
    at div
    at Table (http://localhost:3000/static/js/vendors~main.chunk.js:95475:9)
    at div
    at div
    at ElementList (http://localhost:3000/static/js/vendors~main.chunk.js:422371:24)
    at div
    at div
    at div
    at MultiElementPropertyGrid (http://localhost:3000/static/js/vendors~main.chunk.js:422657:114)
    at div
    at ScrollableWidgetContent (http://localhost:3000/static/js/vendors~main.chunk.js:23773:72)
    at WidgetContent (http://localhost:3000/static/js/vendors~main.chunk.js:69546:20)
    at WidgetContentRenderer (http://localhost:3000/static/js/vendors~main.chunk.js:24132:82)
    at WidgetContentRenderers (http://localhost:3000/static/js/vendors~main.chunk.js:24119:75)
    at div
    at WidgetPanelsComponent (http://localhost:3000/static/js/vendors~main.chunk.js:23558:69)
    at WidgetPanels (http://localhost:3000/static/js/vendors~main.chunk.js:23552:109)
    at WidgetInternals (http://localhost:3000/static/js/vendors~main.chunk.js:69678:133)
    at WidgetPanelsFrontstageComponent
    at WidgetContentManager (http://localhost:3000/static/js/vendors~main.chunk.js:24054:87)
    at CursorTypeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:11285:72)
    at DraggedResizeHandleProvider (http://localhost:3000/static/js/vendors~main.chunk.js:10865:19)
    at DraggedPanelSideProvider (http://localhost:3000/static/js/vendors~main.chunk.js:10861:27)
    at DraggedWidgetIdProvider (http://localhost:3000/static/js/vendors~main.chunk.js:10857:21)
    at DragProvider (http://localhost:3000/static/js/vendors~main.chunk.js:10832:69)
    at NineZoneProvider (http://localhost:3000/static/js/vendors~main.chunk.js:11205:106)
    at NineZone (http://localhost:3000/static/js/vendors~main.chunk.js:11192:13)
    at div
    at ActiveFrontstageDefProvider (http://localhost:3000/static/js/vendors~main.chunk.js:69816:40)
    at WidgetPanelsFrontstage (http://localhost:3000/static/js/vendors~main.chunk.js:69798:112)
    at main
    at ConfigurableUiContent (http://localhost:3000/static/js/vendors~main.chunk.js:39810:108)
    at FrameworkVersion (http://localhost:3000/static/js/vendors~main.chunk.js:48691:86)
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:393848:23)
    at div
    at ThemeManagerComponent (http://localhost:3000/static/js/vendors~main.chunk.js:64240:9)
    at ConnectFunction (http://localhost:3000/static/js/vendors~main.chunk.js:552838:75)
    at IModelViewer (http://localhost:3000/static/js/vendors~main.chunk.js:428932:25)
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:552543:20)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:428716:69
    at IModelLoader (http://localhost:3000/static/js/vendors~main.chunk.js:428809:15)
    at ErrorBoundary (http://localhost:3000/static/js/vendors~main.chunk.js:354037:9)
    at BaseViewer (http://localhost:3000/static/js/vendors~main.chunk.js:428155:23)
    at Viewer (http://localhost:3000/static/js/vendors~main.chunk.js:431180:80)
    at div
    at App (http://localhost:3000/static/js/main.chunk.js:182:89)

**Comment by aruniverse** [comment]
So the warning you're seeing is something we will need to fix. But i don't think its actually what's throwing the error that you're seeing in the viewer. 

Can you check your compatibility with iTwin.js [here](https://connect-imodeljscompatibility.bentley.com/) ?
Are you using a test model from Bentley or is this one of your own?
Have you added any additional code to display decorators or change the graphics?

**Comment by tangytang** [comment]
> Can you check your compatibility
![Screenshot from 2022-05-27 07-23-01](https://user-images.githubusercontent.com/19624580/170595115-d3a98d1b-d038-4822-bbb7-8d4868b37574.png)
atibility with iTwin.js [here](https://connect-imodeljscompatibility.bentley.com/) ?

> Are you using a test model from Bentley or is this one of your own?
I'm using one of the Bentley samples (Stadium Project)

> Have you added any additional code to display decorators or change the graphics?
No

Let me know what kind of debugging information you need. I'll be glad to help.

**Comment by aruniverse** [comment]
Please provide more details like your:

- OS
- Browser (and version number)
- iTwin.js Version

**Comment by tangytang** [comment]
Hi @aruniverse 

See my package.json configuration:

{
  "name": "hdb-tender",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@bentley/icons-generic": "^1.0.34",
    "@bentley/react-scripts": "^4.0.7",
    "@itwin/appui-abstract": "^3.2.0",
    "@itwin/appui-layout-react": "^3.2.0",
    "@itwin/appui-react": "^3.2.0",
    "@itwin/browser-authorization": "^0.5.1",
    "@itwin/components-react": "^3.2.0",
    "@itwin/core-bentley": "^3.2.0",
    "@itwin/core-common": "^3.2.0",
    "@itwin/core-frontend": "^3.2.0",
    "@itwin/core-geometry": "^3.2.0",
    "@itwin/core-i18n": "^3.2.0",
    "@itwin/core-markup": "^3.2.0",
    "@itwin/core-orbitgt": "^3.2.0",
    "@itwin/core-quantity": "^3.2.0",
    "@itwin/core-react": "^3.2.0",
    "@itwin/core-telemetry": "^3.2.0",
    "@itwin/imodel-components-react": "^3.2.0",
    "@itwin/imodels-access-frontend": "^1.0.1",
    "@itwin/imodels-client-management": "^1.0.1",
    "@itwin/itwinui-react": "^1.38.1",
    "@itwin/presentation-common": "^3.2.0",
    "@itwin/presentation-frontend": "^3.2.0",
    "@itwin/reality-data-client": "^0.7.2",
    "@itwin/web-viewer-react": "^2.0.11",
    "@itwin/webgl-compatibility": "^3.2.0",
    "@types/history": "^4.7.11",
    "@types/node": "^14.18.18",
    "@types/react": "^17.0.45",
    "@types/react-dom": "^17.0.17",
    "history": "^4.10.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-redux": "^7.2.8",
    "typescript": "~4.3.0"
  },
  "scripts": {
    "start": "react-scripts --max_old_space_size=4096 start",
    "build": "react-scripts --max_old_space_size=4096 build",
    "test": "react-scripts --max_old_space_size=4096 test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": [
    "last 4 chrome version",
    "last 4 firefox version",
    "last 4 safari version",
    "last 4 ios version",
    "last 4 ChromeAndroid version",
    "last 4 edge version",
    "not dead",
    "not <0.2%"
  ]
}

**Comment by pmconne** [comment]
Thanks for the info @tangytang. This error is most likely the result of your specific graphics card driver having optimized away one of the variables used by a shader program. We compile all of our shaders on Linux, Windows, and macOS without error, but some drivers are smarter about optimizations. We will investigate and fix the shader.
