### ISSUE TITLE
Model not loading since upgraded from 4.0.*

### ISSUE THREAD

**Issue by lijiayi0921** [iTwin/viewer#315]
Hi,
I upgraded my @itwin packages to latest version (4.6.0 as of today), from @itwin/web-viewer-react@4.0.3 and most of the rest 4.0.2.
With the same frontend code, the viewer no longer loads the imodel.
The sign-in, as well as the display of all widgets are working. Custom 3D sprites are loaded, only the imodel is missing.

With Firefox i'm getting this error :
Loading Worker from “http://localhost:3001/viewer/itwin/scripts/parse-imdl-worker.js” was blocked because of a disallowed MIME type (“text/html”).

With Chrome this error : 
Uncaught SyntaxError: Unexpected token '<'
    at handleError (http://localhost:3001/static/js/bundle.js:774837:58)
    at http://localhost:3001/static/js/bundle.js:774856:7
    
Below is my implementation :

>      {isLoggedIn || redirectUrl.pathname !== window.location.pathname ?
                (<Viewer
                    key={'viewer'}
                    iTwinId={props.file?.platformBucket}
                    iModelId={props.file?.platformModel!}
                    authClient={authClient}
                    onIModelAppInit={onIModelAppInit}
                    onIModelConnected={onIModelConnected}
                    additionalI18nNamespaces={['safe', 'safeTools']}
                    uiProviders={[
                        new ViewerNavigationToolsProvider(),
                        new ViewerContentToolsProvider({
                            vertical: {
                                measureGroup: false,
                            },
                        }),
                        new ViewerStatusbarItemsProvider(),
                        new TreeWidgetUiItemsProvider(),
                        new PropertyGridUiItemsProvider(),
                        new MeasureToolsUiItemsProvider(),
                        ...(safeExt?.uiProviders ?? [])
                    ]}
                    viewCreatorOptions={viewCreatorOptions}
                    enablePerformanceMonitors={true}
                />
                ) : null}
        
Any help will be appreciated !

Jiayi

**Comment by lijiayi0921** [comment]
Closed as reposted on itwinjs-core
https://github.com/iTwin/itwinjs-core/issues/6763
